universe.chopper.bot-username=holocron:{universe.chopper.stable.bot-username}
universe.chopper.bot-token=holocron:{universe.chopper.stable.bot-token}
universe.chopper.api-key=holocron:{universe.chopper.stable.api-key}
