spring.config.import=classpath:jocasta-spring.properties,classpath:jocasta-spring-actuator.properties

server.error.whitelabel.enabled=false
# TODO what to do with error paths???
server.error.path=/error
server.shutdown=graceful

spring.web.resources.add-mappings=false
spring.lifecycle.timeout-per-shutdown-phase=10s
