<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ru.prohor.universe</groupId>
        <artifactId>scarif</artifactId>
        <version>final</version>
    </parent>

    <artifactId>scarif-app</artifactId>
    <packaging>jar</packaging>
    <name>scarif-app</name>
    <description>Universe auth service</description>

    <dependencies>
        <dependency>
            <groupId>ru.prohor.universe</groupId>
            <artifactId>jocasta-spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.prohor.universe</groupId>
            <artifactId>scarif-jwt</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.prohor.universe</groupId>
            <artifactId>scarif-jwt-provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.prohor.universe</groupId>
            <artifactId>jocasta-morphia</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>scarif-app</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>ru.prohor.universe.scarif.ScarifMain</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
