universe.chopper.bot-username=holocron:{universe.chopper.local.bot-username}
universe.chopper.bot-token=holocron:{universe.chopper.local.bot-token}
universe.chopper.api-key=holocron:{universe.chopper.local.api-key}
