universe.kenobi.plugins.youtube.tg-bot.username=holocron:{universe.boba-fett.local.bot-username}
universe.kenobi.plugins.youtube.tg-bot.token=holocron:{universe.boba-fett.local.bot-token}
universe.kenobi.plugins.youtube.collection-file.subscribers=${UNIVERSE_WORKSPACE}/kenobi/collections/subscribers.json
