spring.config.import=classpath:chopper-client-local.properties,classpath:jocasta-spring-web.properties
server.port=8080
management.server.port=8081

universe.padawan-kt.chat-id=holocron:{universe.boba-fett.admin-ids}
