spring.config.import=classpath:chopper-client-local.properties,classpath:jocasta-spring-web.properties
server.port=8080
management.server.port=8081

universe.padawan-kt.chat-id=holocron:{universe.boba-fett.admin-ids}

universe.jocasta.spring.filesCacheMaxAgeDays=0
universe.jocasta.spring.pages-dir=${UNIVERSE_HOME}/jawa/padawan-kt/content/pages
universe.jocasta.spring.pages-list=music-player
universe.jocasta.spring.root=${UNIVERSE_HOME}/jawa/padawan-kt/content
