spring.config.import=classpath:chopper-client-local.properties

### Legacy Yahtzee ###
universe.yahtzee.legacy.output-path=${UNIVERSE_HOME}/../IdeaProjects/tmpYahtzee/games
universe.yahtzee.legacy.mobile-output-path=${UNIVERSE_HOME}/../IdeaProjects/tmpYahtzee/games-mobile
