spring.config.import=classpath:jocasta-spring.properties

### Telegram Bot ###
universe.boba-fett.admin-ids=holocron:{universe.boba-fett.admin-ids}
universe.boba-fett.admin-link=holocron:{universe.boba-fett.admin-link}
universe.boba-fett.holidays-path=${UNIVERSE_HOME}/jawa/boba-fett/holidays

### Data Files ###
universe.boba-fett.collection-file.users=${UNIVERSE_WORKSPACE}/boba-fett/collections/users.json
universe.boba-fett.collection-file.custom-holidays=${UNIVERSE_WORKSPACE}/boba-fett/collections/custom-holidays.json
universe.boba-fett.collection-file.currency-rates=${UNIVERSE_WORKSPACE}/boba-fett/collections/currency-rates.json
