spring.config.import=classpath:jocasta-spring-web.properties
server.port=7001
management.server.port=7051

### Scarif ###
universe.scarif.access-token.ttl=5m
universe.scarif.refresh-token.cookie-name=scarif_refresh_token
universe.scarif.refresh-token.ttl=90d
universe.scarif.refresh-token.rotate-window=10s

### Snowflake ###
universe.jocasta.core.snowflake.worker-id=1

### Mongo ###
universe.scarif.collection-file.users=${UNIVERSE_WORKSPACE}/scarif/collections/users.json

### Google OAuth ###
universe.scarif.oauth.google.auth-url=https://accounts.google.com/o/oauth2/v2/auth
universe.scarif.oauth.google.token-exchange-url=https://oauth2.googleapis.com/token
universe.scarif.oauth.google.redirect-url=${universe.scarif.host}/api/oauth/google/callback
universe.scarif.oauth.google.jwk-set-url=https://www.googleapis.com/oauth2/v3/certs
universe.scarif.oauth.google.jwk-set-cache-ttl=3h
universe.scarif.oauth.google.issuer=https://accounts.google.com
