### Scarif ###
universe.scarif.host=http://localhost:7001
universe.scarif.frontend-host=http://localhost:7009
universe.scarif.private-key=holocron:{universe.scarif.local.private-key}
universe.scarif.public-key=holocron:{universe.shared.local.public-key}
universe.scarif.allowed-origins=*
universe.scarif.refresh-token.same-site=Lax
universe.scarif.refresh-token.secure=false

### Google OAuth ###
universe.scarif.oauth.google.client-id=holocron:{universe.scarif.oauth.google.local.client-id}
universe.scarif.oauth.google.client-secret=holocron:{universe.scarif.oauth.google.local.client-secret}
