### Scarif ###
universe.scarif.host=holocron:{universe.scarif.stable.host}
universe.scarif.frontend-host=holocron:{universe.scarif.stable.frontend-host}
universe.scarif.private-key=holocron:{universe.scarif.stable.private-key}
universe.scarif.public-key=holocron:{universe.scarif.stable.public-key}
universe.scarif.allowed-origins=holocron:{universe.scarif.stable.allowed-origins}
universe.scarif.refresh-token.same-site=None
universe.scarif.refresh-token.secure=true

### Google OAuth ###
universe.scarif.oauth.google.client-id=holocron:{universe.scarif.oauth.google.stable.client-id}
universe.scarif.oauth.google.client-secret=holocron:{universe.scarif.oauth.google.stable.client-secret}
