spring.config.import=classpath:chopper-client-local.properties,classpath:jocasta-spring-web.properties
server.port=8080
management.server.port=8081

universe.jocasta.mongo.host=holocron:{universe.shared.test.mongo.host}
universe.jocasta.mongo.port=holocron:{universe.shared.test.mongo.port}
universe.jocasta.mongo.user=holocron:{universe.shared.test.mongo.user}
universe.jocasta.mongo.password=holocron:{universe.shared.test.mongo.password}
universe.jocasta.mongo.database=holocron:{universe.shared.test.mongo.database}

universe.jocasta.spring.filesCacheMaxAgeDays=0
universe.jocasta.spring.pages-dir=${UNIVERSE_HOME}/jawa/padawan/content/pages
universe.jocasta.spring.pages-list=
universe.jocasta.spring.root=${UNIVERSE_HOME}/jawa/padawan/content

universe.padawan.chat-id=holocron:{universe.boba-fett.admin-ids}
